version: "3"
services:

   db:
     image: postgres:15
     restart: always
     environment:
       POSTGRES_PASSWORD: ifescritorio
       POSTGRES_DB: ifescritorio
     ports:
       - 5433:5432
     volumes:
       - ./postgres-data:/bitnami/postgresql/data
